import { Comic_Neue } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";

const comicNeue = Comic_Neue({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-comic-neue', // optional for CSS variables usage
});

export const metadata: Metadata = {
  title: "Fasika Child Care Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={comicNeue.className}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}