import './globals.css';
import HydrationGuard from './HydrationGuard';

export const metadata = {
  title: "Fasika Child Care Center",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ fontFamily: "'Comic Neue', sans-serif" }}>
      <body className="antialiased">
        <HydrationGuard>{children}</HydrationGuard>
      </body>
    </html>
  );
}